import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/providers/reduxProvider";
import SiteHeader from "@/components/site/layout/header";
import SiteFooter from "@/components/site/layout/footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black"
      >
        <ReduxProvider>
          <SiteHeader />
          {children}

          <SiteFooter />
        </ReduxProvider>
      </body>
    </html>
  );
}
